events {}

http {
    upstream my_apps {
        server app:3000; # Nama service 'app' dari docker-compose
    }

    server {
        listen 80;

        location / {
            proxy_pass http://my_apps;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}